[package]
name = "aiports"
version = "0.1.0"
authors = ["murano <murano1980@gmail.com>"]

[dependencies]
actix = "0.5.2"
actix-web = "0.4.5"
env_logger = "0.5"
log = "0.4"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
futures = "0.1"
